# code: language=ansible
- name: Setup Docker repo in apt
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "{{ docker_uri }}"
    signed_by: "{{ docker_uri }}/gpg"
    suites: "{{ ansible_distribution_release }}"
    components: stable

- name: Install docker
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Get current user
  ansible.builtin.command:
    cmd: whoami
  register: user_name
  changed_when: false

- name: Assign docker group to user
  block:
    - name: Ensure docker group
      become: true
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to group
      become: true
      ansible.builtin.user:
        user: "{{ user_name.stdout | trim }}"
        append: true
        groups:
          - docker
