# code: language=ansible
# kudos to https://gist.github.com/roib20/27fde10af195cee1c1f8ac5f68be7e9b?permalink_comment_id=4980485#gistcomment-4980485
- name: Setup kubernetes repo in apt
  become: true
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: [deb]
    uris: "{{ kubectl_uri }}"
    signed_by: "{{ kubectl_signed_by }}"
    suites: [/]
    state: present
    enabled: true

- name: Install kubectl
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - kubectl
      - bash-completion

- name: Add entry to bashrc
  ansible.builtin.lineinfile:
    path: "$HOME/.bashrc"
    line: 'source <(kubectl completion bash) # managed by Ansible'
