"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$directory\
$git_branch$git_status \
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$time\
$line_break$username $character\
"""

# Prompt specific config

[character]
success_symbol = "[->](bold green)"
error_symbol = "[->](bold red)"

[cmd_duration]
format = '\[[$duration]($style)\]'

[directory]
home_symbol = "~"
truncate_to_repo = true

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[os]
format = '\[[$symbol]($style)\]'

[sudo]
format = '\[[as $symbol]\]'

[time]
format = '[$time]($style)'
disabled = false

[username]
format = '[$user]($style)'
show_always = true
style_user = "yellow bold"
style_root = "red bold"

# Tools specific config

[docker_context]
format = '\[[$symbol$context]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '[$symbol$branch]($style)'

[git_status]
format = '( [\[$all_status$ahead_behind\]]($style))'

[helm]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

# Language specific config

[package]
format = '\[[$symbol$version]($style)\]'

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[bun]
format = '\[[$symbol($version)]($style)\]'

[c]
format = '[\[$symbol($version(-$name))\]]($style)'

[deno]
format = '\[[$symbol($version)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[golang]
format = '\[[$symbol($version)]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[java]
format = '\[[$symbol($version)]($style)\]'

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[php]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
python_binary = ["./.venv/bin/python", "./.env/bin/python", "python3"]

[rust]
format = '\[[$symbol($version)]($style)\]'
